version: '3'

services:
  app:
    build:
      context: .
    image: urlshortener
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 9292:9292
    env_file:
      - .env
    networks:
      - urlshortener-network

  db:
    image: postgres:13.11-bullseye
    restart: unless-stopped
    ports:
      - 5432
    environment:
      - POSTGRES_DB=urlshortener
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - urlshortener-network

volumes:
  pgdata:

networks:
  urlshortener-network:
    driver: bridge